apiVersion: v1
kind: Service
metadata:
  name: micro-keyvaluestore
  namespace: default
spec:
  type: ClusterIP
  selector:
    case: micro-keyvaluestore
  ports:
  - protocol: TCP
    port: 80
    targetPort: app-port

---

apiVersion: v1
kind: Service
metadata:
  name: micro-master
  namespace: default
spec:
  type: ClusterIP
  selector:
    case: micro-master
  ports:
  - protocol: TCP
    port: 80
    targetPort: app-port

--- 

apiVersion: v1
kind: Service
metadata:
  name: micro-db
  namespace: default
spec:
  type: ClusterIP
  selector:
    case: micro-db
  ports:
  - protocol: TCP
    port: 80
    targetPort: app-port

--- 

apiVersion: v1
kind: Service
metadata:
  name: micro-storage
  namespace: default
spec:
  type: ClusterIP
  selector:
    case: micro-storage
  ports:
  - protocol: TCP
    port: 80
    targetPort: app-port
